[project]
name = "hproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Morrison", email = "dm236@st-andrews.ac.uk" }
]
requires-python = ">=3.12"
dependencies = [
    "cuml-cu12[dask]>=26.2.0",
    "dotenv>=0.9.9",
    "matplotlib>=3.10.8",
    "scikit-dimension>=0.3.4",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.3",
]

[project.scripts]
hproj = "hproj.__main__:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
docstring-code-format = true

[dependency-groups]
dev = [
    "black>=26.3.0",
    "ruff>=0.15.5",
]
