datasets:
  - kather100k
  - spider-colorectal

encoders:
  - uni2
  - dinov2

seeds: 
  calibration: 
    projector: [0]
    classifier: [1]
  curve: [2, 3]
  evaluation: [4]

num_folds: 2

calibration:
  projector:
    select: mean-knn-score-mean
    subsample: 10000
    dimensions: [2, 4, 8]
    measurements:
      - name: mean-knn-score
        params:
          ks: [5]
    projectors:
      - name: pca
        params: {}
      - name: grp
        params: {}
      - name: umap
        params:
          n_neighbors: [5, 20]
          min_dist: [0.1, 0.5]
          metric: [cosine]

  classifier:
    select: accuracy
    subsample: 10000
    dimensions: [2, 4]
    classifiers:
      - name: logistic-regression
        params:
          C: [1.0]
          max_iter: [200]

curve:
  dimension_intervals:
    - start: 1
      stop: 50
      step: 1
    - start: 50
      stop: 1024
      step: 32
  include_full_dimension: false
  subsample: 10000
  projectors: ['pca', 'umap', 'grp']
  classifiers: ['logistic-regression']
  measurements:
    - name: mean-knn-score
      params:
        ks: [5]

thresholds:
  metrics: ['accuracy', 'roc_auc']
  conditions: [0.99, 0.95]

intrinsic_dims:
  subsample: 5000

report:
  detail_dims: 50

generalisation:
  measurements:
    - name: mean-knn-score
      params:
        ks: [5]
  projectors:
    - name: pca
      params: {}
    - name: grp
      params: {}
    - name: umap
      params:
        n_neighbors: [5, 20]
        min_dist: [0.1, 0.5]
        metric: [cosine]
  classifiers:
    - name: logistic-regression
      params:
        C: [1.0]
        max_iter: [200]
