datasets:
  - kather100k
  - spider-colorectal

encoders:
  - uni2

# paired seeds
seeds: 
  calibration: 
    projector: [0, 1]
    classifier: [2, 3]
  curve: [4, 5]
  evaluation: [0, 1, 2, 3, 4, 5]

# set the number of folds for cross-validation
num_folds: 3

calibration:
  projector:
    select: mean-knn-score-mean
    subsample: 1000  # subsample each dataset down to 1k (about 1%)
    dimensions: [2,8]
    measurements:
      - name: mean-knn-score
        params:
          ks: [5,30]
      - name: silhouette-score
        params:
          {}
      - name: trustworthiness
        params:
          {}
    projectors:
      - name: pca
        params:
          {}
      - name: grp
        params:
          {}
      - name: umap
        params:
          n_neighbors: [5, 30]
          min_dist: [0.25, 0.5]
          metric: [cosine]  # these are image embeddings
  classifier:
    select: 'roc_auc'
    subsample: 1000  # subsample each dataset down to 1k (about 1%)
    dimensions: [2,8]
    classifiers:
      - name: logistic-regression
        params:
          C: [0.01, 0.1, 1, 10, 100]

curve:
  dimension_intervals:
    - start: 2
      stop: 4
      step: 1
    - start: 8
      stop: 10
      step: 1
  subsample: 1000
  projectors: ['pca', 'umap', 'grp']
  classifiers: ['logistic-regression']
  measurements:
    - name: mean-knn-score
      params:
        ks: [5,30]
    - name: silhouette-score
      params:
        {}
    - name: trustworthiness