datasets:
  - kather100k
  - spider-colorectal

encoders:
  - uni2

# paired seeds
seeds: 
  calibration: 
    projector: [0, 1]
    classifier: [2, 3]
  curve: [4, 5]
  evaluation: [0, 1, 2, 3, 4, 5]

# set the number of folds for cross-validation
num_folds: 3

calibration:
  projector:
    select: mean-knn-score-mean
    subsample: 1000  # subsample each dataset down to 1k (about 1%)
    dimensions: [2,8]
    measurements:
      - name: mean-knn-score
        params:
          ks: [5,30]
      - name: silhouette-score
        params:
          {}
      - name: trustworthiness
        params:
          {}
    projectors:
      - name: pca
        params:
          {}
      - name: grp
        params:
          {}
      - name: umap
        params:
          n_neighbors: [5, 30]
          min_dist: [0.25, 0.5]
          metric: [cosine]  # these are image embeddings
  classifier:
    select: 'roc_auc'
    subsample: 1000  # subsample each dataset down to 1k (about 1%)
    dimensions: [2,8]
    classifiers:
      - name: logistic-regression
        params:
          C: [0.01, 0.1, 1, 10, 100]
          max_iter: [2000]
          linesearch_max_iter: [300]
          tol: [1.0e-5]

curve:
  dimension_intervals:
    - start: 2
      stop: 4
      step: 1
    - start: 8
      stop: 10
      step: 1
  include_full_dimension: false
  subsample: 1000
  projectors: ['pca', 'umap', 'grp']
  classifiers: ['logistic-regression']
  measurements:
    - name: mean-knn-score
      params:
        ks: [5,30]
    - name: silhouette-score
      params:
        {}
    - name: trustworthiness

thresholds:
  metrics: ['accuracy', 'roc_auc']
  conditions: [0.99, 0.95]

generalisation:
  measurements:
    - name: mean-knn-score
      params:
        ks: [5,30]
    - name: silhouette-score
      params: {}
    - name: trustworthiness
      params: {}
  projectors:
    - name: pca
      params: {}
    - name: grp
      params: {}
    - name: umap
      params:
        n_neighbors: [5, 30]
        min_dist: [0.25, 0.5]
        metric: [cosine]  # these are image embeddings
  classifiers:
    - name: logistic-regression
      params:
        C: [0.01, 0.1, 1, 10, 100]
        max_iter: [2000]
        linesearch_max_iter: [300]
        tol: [1.0e-5]
    - name: mlp
      params:
        hidden_layer_sizes: [[50], [100, 50]]
        activation: ['relu', 'tanh']
        solver: ['adam']
        alpha: [0.0001, 0.001]
        learning_rate: ['constant']
        learning_rate_init: [0.001]
        max_iter: [200]
        early_stopping: [True]
    - name: xgboost
      params:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.3]
        max_depth: [3, 10]
        min_child_weight: [1, 8]
        subsample: [0.6, 1.0]
        colsample_bytree: [0.6, 1.0]
        gamma: [0, 0.5]
        reg_lambda: [0.001, 10.0]
        reg_alpha: [0.001, 10.0]
